### ISSUE TITLE
Cities without opening hours

### ISSUE THREAD

**Issue by ubergesundheit** [CodeforLeipzig/wo-ist-testzentrum#2]
How should cities without published opening hours be handeled?

Münster already has https://codeformuenster.org/corona-testungen/ but the official page does not publish opening hours.

Any idea how to handle this?

**Comment by joliyea** [comment]
I simply added 'keine Angabe' like so:

```json
{
    "geometry": {
        "coordinates": [
            "8.536862",
            "50.335011"
        ],
        "type": "Point"
    },
    "properties": {
        "location": "Obergasse 13 61250 Usingen",
        "telephone": "06081 66742",
        "details_url": "keine Angabe",
        "opening_hours": "keine Angabe",
        "title": "Adler Apotheke",
        "hints": [
            "Nur mit telefonische Anmeldung.",
            "PCR-Test: nein",
            "Terminbuchung notwendig: ja"
        ]
    },
    "type": "Feature"
}
```

**Comment by joergreichert** [comment]
With "keine Angabe" the marker won't appear on the map in any category ("jetzt", "heute", "alle", "sonstige"). Not sure yet what to set in opening hours to end up in "sonstige". Maybe we need more categories (like appointment only be phone, appointment only online). Even then maybe opening hours needs to be differ between time range, where I'm able to make an appointment (when will be someone on the phone), and time range when I can really go there to do the test.

**Comment by joliyea** [comment]
Good point. How should it be handled instead?

**Comment by johnjohndoe** [comment]
Did you try to use the `opening_hours_unclassified` property as stated in the [contribution guide](https://github.com/CodeforLeipzig/wo-ist-testzentrum/blob/master/CONTRIBUTING.md#market-data-format-specification)?

> Opening hours which cannot be expressed in that format can use the `opening_hours_unclassified` property. In that case set the `opening_hours` property to `null`.

These markers should appear under "Sonstige".

**Comment by joergreichert** [comment]
Didn't get it working.

**Comment by joergreichert** [comment]
Ok, finally found my mistake. I was pushing to the wrong remote :relieved:
